version: '3'
services:
  apacheds:
    image: tgbyte/apacheds:2.0.0.AM26
    container_name: apacheds
    hostname: apacheds
    environment:
      TZ: ${TZ}
    restart: always
    ports: 
      - "10389:10389"
      - "10636:10636"
